sudo: required
language: python
services:
  - podman
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq --yes install podman


install:
  - pip install molecule
  - pip install molecule-podman
script:
  - molecule test
