sudo: required
language: python
before_install:
  - sudo apt-get update
  - sudo apt-get install -y software-properties-common
  - sudo add-apt-repository -y ppa:projectatomic/ppa
  - sudo apt-get update
  - sudo apt-get install -y podman
  - pwd
  - test

install:
  - pip install molecule
  - pip install molecule-podman
  - pip install ansible-core==2.11.2
script:
  - molecule test
