sudo: required
language: python
before_install:
  - sudo apt-get update
  - sudo apt-get install -y software-properties-common
  - sudo add-apt-repository -y ppa:projectatomic/ppa
  - sudo apt-get update
  - sudo apt-get install -y podman
  - pwd

install:
  - pip install -r requirements.txt
script:
  - molecule test
