---
- name: start
  debug:
    msg: "Start disk stat"

- name: diskspace module
  training.demo.diskspace:
    path: /tmp
    storage: true
  register: output

- name: disk stat output
  debug:
    msg: "{{ output }}"

- name: end
  debug:
    msg: "End disk stat"
